import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import ThemeProvider from "@/components/theme/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The road to next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Header />
          <main className="px-8 py-24 overflow-y-auto overflow-x-hidden min-h-screen flex-1 flex flex-col bg-secondary/20">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
